spring:
  application:
    name: choogoomoneyna!

  config:
    import: optional:application-secret-kakao.yml

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            redirect-uri: ${kakao.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: ${kakao.auth-uri}
            token-uri: ${kakao.token-uri}
            user-info-uri: ${kakao.user-info-uri}
            user-name-attribute: id
