name: Deploy to EC2 with Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build WAR with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Save Docker image to tar
        run: docker save myapp:latest > myapp.tar

      - name: Copy image and env file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            myapp.tar
          target: "~/"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # env.b64 파일 생성
            echo "${{ secrets.ENV_B64 }}" | base64 -d > .env

            # 기존 컨테이너/이미지 정리
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker rmi myapp:latest || true

            # 이미지 로드
            sudo docker load < myapp.tar

            # --env-file 옵션으로 .env 읽어서 컨테이너 실행
            sudo docker run -d --name myapp -p 80:8080 \
              --restart always \
              --env-file .env \
              myapp:latest
