name: Deploy to EC2 with Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build WAR with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Save Docker image to tar
        run: docker save myapp:latest > myapp.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: myapp.tar
          target: "~/"

      - name: Restore .env on EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/appconfig
            echo "${{ secrets.APP_ENV_B64 }}" | base64 -d > /home/ubuntu/appconfig/.env

            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker rmi myapp:latest || true

            sudo docker load < myapp.tar

            sudo docker run -d --name myapp -p 80:8080 \
              --restart always \
              --env-file /home/ubuntu/appconfig/.env \
              myapp:latest
